### ISSUE TITLE
Summer Logo Artwork & Animation

### ISSUE THREAD

**Issue by AJtheCrocodile** [discordexperimenthub/deh-assets#6]
GIF ![IMG_5933](https://github.com/discordexperimenthub/deh-assets/assets/138383996/ebdfdd4f-1b13-4b26-8ddb-60d23d095cc5)
PNG ![IMG_5934](https://github.com/discordexperimenthub/deh-assets/assets/138383996/d59372fb-3616-44f3-b5fa-933e738c2adf)
Logo without the drink toppings ![IMG_5935](https://github.com/discordexperimenthub/deh-assets/assets/138383996/ff8f8a86-9528-432d-9e37-fbdecd8b1e0e)
Regular logo with wave ![IMG_5937](https://github.com/discordexperimenthub/deh-assets/assets/138383996/d0b06ef7-1992-4f2d-96d4-5032e3a5dfc4)

**Comment by Tolga1452** [comment]
Thank you again!
